---
ntp_service_name: ntp
ssh_service_name: ssh
nfs_service: nfs-kernel-server
nrpe_service_name: nagios-nrpe-server
nagios_plugins_directory: /usr/lib/nagios/plugins

ceph_packages_to_remove:
  - ceph
  - ceph-common
  - libcephfs1
  - radosgw
  - python-ceph
  - python-rados
  - librbd1
  - librados2

packages: []
common_packages: []

apt_repos: []
common_apt_repos: []
