---
ntp_service_name: ntpd
ssh_service_name: sshd
nrpe_service_name: nrpe
nagios_plugins_directory: /usr/lib64/nagios/plugins

# ceph packages that we ensure do not exist
ceph_packages_to_remove:
  - ceph
  - ceph-common
  - ceph-debuginfo
  - ceph-release
  - libcephfs1
  - ceph-radosgw
  - python-ceph
  - python-rados
  - librbd1
  - librados2
